name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-platform:
    name: Build Platform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      # - name: Check format
      #   id: yarn-format-check
      #   run: yarn prettier:check

      # - name: Check linting
      #   id: yarn-lint-check
      #   run: yarn lint:all

      # - name: Test
      #   id: yarn-test
      #   run: yarn test:all

      # - name: Compile Typescript
      #   id: yarn-tsc
      #   run: yarn tsc:full

  # test-typescript:
  #   name: TypeScript Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       id: setup-node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version-file: .node-version
  #         cache: yarn

  #     - name: Install Dependencies
  #       id: npm-ci
  #       run: npm ci

  #     - name: Check Format
  #       id: npm-format-check
  #       run: npm run format:check

  #     - name: Lint
  #       id: npm-lint
  #       run: npm run lint

  #     - name: Test
  #       id: npm-ci-test
  #       run: npm run ci-test

  # test-action:
  #   name: GitHub Actions Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         milliseconds: 2000

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.time }}"